export const CAROUSEL_CREATE_REQUEST = "CAROUSEL_CREATE_REQUEST";
export const CAROUSEL_CREATE_SUCCESS = "CAROUSEL_CREATE_SUCCESS";
export const CAROUSEL_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const CAROUSEL_GET_REQUEST = "CAROUSEL_GET_REQUEST";
export const CAROUSEL_GET_SUCCESS = "CAROUSEL_GET_SUCCESS";
export const CAROUSEL_GET_FAIL = "ORDER_GET_FAIL";

export const CAROUSEL_DELETE_REQUEST = "CAROUSEL_DELETE_REQUEST";
export const CAROUSEL_DELETE_SUCCESS = "CAROUSEL_DELETE_SUCCESS";
export const CAROUSEL_DELETE_FAIL = "ORDER_DELETE_FAIL";
