export const SELLER_LIST_REQUEST = "SELLER_LIST_REQUEST";
export const SELLER_LIST_SUCCESS = "SELLER_LIST_SUCCESS";
export const SELLER_LIST_FAIL = "SELLER_LIST_FAIL";

export const SELLER_DETAILS_REQUEST = "SELLER_DETAILS_REQUEST";
export const SELLER_DETAILS_SUCCESS = "SELLER_DETAILS_SUCCESS";
export const SELLER_DETAILS_FAIL = "SELLER_DETAILS_FAIL";

export const SELLER_CREATE_REQUEST = "SELLER_CREATE_REQUEST";
export const SELLER_CREATE_SUCCESS = "SELLER_CREATE_SUCCESS";
export const SELLER_CREATE_FAIL = "SELLER_CREATE_FAIL";
export const SELLER_CREATE_RESET = "SELLER_CREATE_RESET";
